# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fa229a414af9bfdfeda296f79498e935b1bf2dcc2e239c8060c96a5fbb76f3e93ce2b504d488b305aa5f3ca8dbcd85cc15e031bb975af3a023f354492bc8054

test:
  secret_key_base: 29488e6773c87affde4521f4842aa49543f1b79effa99b967c2207eee06f9818739671ce98823eb9c910771883ffe7e183bbe4efb6f0b94613fa36cd84364fd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
